import "./globals.css";
import { Merriweather } from "next/font/google";

import NavigationBar from "./components/UI/NavigationBar";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Virac Special",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-vs-gray`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
